package com.genai.knowitall.controller.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Response DTO for answering a user's query in the RAG system.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class QueryResponse {

    /**
     * The generated answer to the user's question
     * Generated by LLM based on retrieved context.
     * If isGrounded=false, this is best-guess from limited context
     */
    private String answer;

    /**
     * Confidence score (0-1) based on max similarity of retrieved chunks.
     * 1.0 = highly confident (strong context found).
     * 0.0 = not confident (weak context or no context).
     * Used to signal to UI whether answer is reliable.
     */
    private Double confidence;

    /**
     * Whether the answer is grounded in retrieved context.
     * true: confidence >= confidenceThreshold.
     * false: best-guess answer, confidence < threshold.
     * UI should display different styling/warning based on this.
     */
    private Boolean isGrounded;

    /**
     * List of source documents/chunks that were used to generate the answer
     * Empty if no relevant context found
     * Allows user to verify sources and read full context
     */
    private List<SourceReference> sources;

    /**
     * Number of chunks actually retrieved (may be < requested topK)
     */
    private Integer chunksRetrieved;

    /**
     * Time taken for semantic search in vector store (milliseconds)
     */
    private Long retrievalTimeMs;

    /**
     * Time taken for LLM to generate answer (milliseconds)
     */
    private Long generationTimeMs;

    /**
     * Total end-to-end time for the query (milliseconds)
     */
    private Long totalTimeMs;

    /**
     * Optional error message if something went wrong
     */
    private String error;
}
